# Generated by Django 6.0.1 on 2026-01-21 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AdCrawl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friendlyName", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("campaign", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("approved", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("run_through", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Ad Crawl",
                "verbose_name_plural": "Ad Crawls",
            },
        ),
    ]
