# Generated by Django 6.0.1 on 2026-01-21 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="adcrawl",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RenameField(
            model_name="adcrawl",
            old_name="friendlyName",
            new_name="friendly_name",
        ),
        migrations.AddField(
            model_name="adcrawl",
            name="can_run_on_stars",
            field=models.BooleanField(default=False),
        ),
    ]
