# Generated by Django 6.0.1 on 2026-01-21 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0002_rename_is_active_adcrawl_active_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcrawl",
            name="can_run_on_stars",
            field=models.BooleanField(default=False, verbose_name="Can run on STARs"),
        ),
        migrations.AlterField(
            model_name="adcrawl",
            name="run_through",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
