# Generated by Django 6.0.1 on 2026-01-21 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0003_alter_adcrawl_can_run_on_stars_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="adcrawl",
            name="approved",
            field=models.BooleanField(
                default=False,
                help_text="set this to true, crawl management staff get their own model",
            ),
        ),
        migrations.AlterField(
            model_name="adcrawl",
            name="run_through",
            field=models.DateTimeField(
                blank=True, help_text="Leave blank to run forever.", null=True
            ),
        ),
        migrations.CreateModel(
            name="AdCrawlRequests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("friendly_name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("campaign", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Crawl Request",
                "verbose_name_plural": "Ad Crawl Requests",
            },
        ),
    ]
