# Generated by Django 6.0.1 on 2026-01-21 17:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0004_alter_adcrawl_approved_alter_adcrawl_run_through_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adcrawl",
            name="approved",
        ),
        migrations.AlterField(
            model_name="adcrawlrequests",
            name="requested_by",
            field=models.ForeignKey(
                help_text="Set this to yourself. WE KNOW WHO YOU ARE.",
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
