# Generated by Django 6.0.1 on 2026-01-21 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0005_remove_adcrawl_approved_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="adcrawl",
            name="acid",
            field=models.IntegerField(
                default=2345193459172356419732645192634912634,
                help_text="The unique ID for this ad crawl.",
                unique=True,
            ),
            preserve_default=False,
        ),
    ]
