# Generated by Django 6.0.1 on 2026-01-21 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0006_adcrawl_acid"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adcrawl",
            name="acid",
        ),
    ]
