# Generated by Django 6.0.1 on 2026-01-29 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0007_remove_adcrawl_acid"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="adcrawl",
            name="active",
        ),
        migrations.AddField(
            model_name="adcrawl",
            name="reason_for_denial",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="adcrawl",
            name="status",
            field=models.IntegerField(
                default=0, help_text="0 = awaiting moderation, 1 = approved, 2 = denied"
            ),
        ),
        migrations.CreateModel(
            name="AdCrawlUserPerms",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("can_moderate", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Ad Crawl User Permission",
                "verbose_name_plural": "Ad Crawl User Permissions",
            },
        ),
        migrations.DeleteModel(
            name="AdCrawlRequests",
        ),
    ]
