# Generated by Django 6.0.1 on 2026-01-29 23:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("adcrawls", "0008_remove_adcrawl_active_adcrawl_reason_for_denial_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="adcrawl",
            name="creator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="adcrawluserperms",
            name="can_edit_others_crawls",
            field=models.BooleanField(default=False),
        ),
    ]
