# Generated by Django 6.0.1 on 2026-01-29 23:18

import agents.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Agent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="This is for your reference", max_length=100
                    ),
                ),
                (
                    "api_key",
                    models.CharField(default=agents.models.keygenerator, unique=True),
                ),
                (
                    "rate_limit",
                    models.IntegerField(
                        default=1600,
                        help_text="Ensure your agent implementation does not go over this number of requests in 2 hours.",
                    ),
                ),
                ("last_polled_songrequests", models.DateTimeField(auto_now=True)),
                (
                    "last_ip_address",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
            ],
        ),
    ]
