; AMRSystem Agent Configuration File.
; Note, the only official places to get agent executables from are:
; 1. https://semistatic.fourteentrees.net/amrs-agent/, AND
; 2. https://github.com/fourteentrees/AMRSystem/releases.
[ServerSettings]
; Base URL to your AMRSystem installation (no trailing slash)
host = ""
; create this in the admin dashboard
key = ""

[ClientSettings]
; determines how ad crawls are sent
; STAR will send it to DfltConfig.xml
; OBS sends crawls to a text file
type = "OBS"
; enable ad crawls?
EnableCrawls = True
; enable music requests?
EnableMusicReqs = False
; OBS websocket url
OBSWebSocketURL = "ws://localhost:4455"
OBSWebSocketPassword = ""

[AdCrawlSettings]
; Set this to your flavor's ad crawl directory for STARs,
; or anywhere readable by OBS for OBS.
; ENSURE THE AGENT HAS WRITE ACCESS HERE
CrawlSaveLocation = "C:\Users\YourUser\crawl.txt"
; How often (in minutes) ad crawl pulls are made.
CrawlCycleInterval = 15

[MusicRequestSettings]
; Set this to a writable directory. The agent will save music requests here.
; ENSURE THE AGENT HAS WRITE ACCESS HERE
RequestSaveLocation = "C:\Users\YourUser\amrs-agent-requests"
; How often (in minutes) music request pulls are made.
; Set this relatively low so your viewers dont complain about untimely requests,
; but not low enough to be DoS your server.
RequestCycleInterval = 2
