# Generated by Django 6.0.1 on 2026-01-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songrequests", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="song",
            name="album",
            field=models.CharField(default="Single", max_length=200),
        ),
    ]
